<h1 style="color: blue; text-align: center;">Deep Learning</h1>
<h2 style="color: blue; text-align: center;">Homework 1</h2>
<h2 style="color: green; text-align: center;">Poorya MohammadiNasab</h2>
<h2 style="color: green; text-align: center;">400722138</h2>


## 2.1.8. Exercises

In [1]:
import torch

In [2]:
x = torch.arange(12, dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [3]:
x.shape

torch.Size([12])

In [4]:
x.numel()

12

In [5]:
X = x.reshape(3, 4)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [6]:
X.shape

torch.Size([3, 4])

In [7]:
X.numel()

12

In [8]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [9]:
torch.ones((3, 4))

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [10]:
torch.randn(3, 4)

tensor([[-0.6059,  0.1687, -0.2701,  0.2875],
        [ 0.4469, -1.3740, -0.1324,  0.8488],
        [-0.9613,  0.7421,  0.5657,  1.5737]])

In [11]:
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [12]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y  # The ** operator is exponentiation

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [13]:
torch.exp(x) # e^x

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [14]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [15]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [16]:
X > Y

tensor([[False, False, False, False],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])

In [17]:
X < Y

tensor([[ True, False,  True, False],
        [False, False, False, False],
        [False, False, False, False]])

In [18]:
X.sum()

tensor(66.)

In [19]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [20]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [21]:
X[-1], X[1:4]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [22]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [23]:
X[1, 2] = 9
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [24]:
X[0:2, :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

In [25]:
before = id(Y)
Y = Y + X
id(Y) == before

False

In [26]:
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = X + Y
print('id(Z):', id(Z))

id(Z): 1734595123296
id(Z): 1734595123296


In [27]:
before = id(X)
X += Y
id(X) == before

True

In [28]:
A = X.numpy()
B = torch.from_numpy(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [29]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

In [45]:
A = torch.randint(0,10,(2,3,4))
B = torch.randint(0,10,(2,3,4))
print('A')
print(A)
print('B')
print(B)
print('A + B') 
print(A + B)

A
tensor([[[1, 1, 6, 8],
         [3, 3, 4, 4],
         [9, 7, 1, 7]],

        [[3, 1, 3, 6],
         [9, 8, 9, 6],
         [1, 9, 8, 3]]])
B
tensor([[[5, 7, 6, 2],
         [0, 2, 4, 0],
         [5, 3, 8, 2]],

        [[4, 2, 3, 2],
         [0, 7, 0, 1],
         [9, 0, 0, 7]]])
A + B
tensor([[[ 6,  8, 12, 10],
         [ 3,  5,  8,  4],
         [14, 10,  9,  9]],

        [[ 7,  3,  6,  8],
         [ 9, 15,  9,  7],
         [10,  9,  8, 10]]])


In [46]:
A = torch.randint(0,10,(1,3,4))
B = torch.randint(0,10,(2,3,4))
print('A')
print(A)
print('B')
print(B)
print('A + B') 
print(A + B)

A
tensor([[[3, 0, 6, 8],
         [3, 3, 5, 8],
         [1, 4, 2, 2]]])
B
tensor([[[8, 9, 0, 7],
         [8, 5, 4, 9],
         [1, 9, 2, 8]],

        [[2, 7, 4, 9],
         [1, 1, 0, 5],
         [7, 9, 2, 5]]])
A + B
tensor([[[11,  9,  6, 15],
         [11,  8,  9, 17],
         [ 2, 13,  4, 10]],

        [[ 5,  7, 10, 17],
         [ 4,  4,  5, 13],
         [ 8, 13,  4,  7]]])


## 2.2.5. Exercises

#### Create a raw dataset with more rows and columns.

In [47]:
import pandas as pd

In [73]:
df = pd.read_csv('./Dataset/Sample_Data.csv',header=None)

In [74]:
df.head()

0     1      2     3     4     5   6
0  35.3  2.60    NaN  42.4  24.2  47.1  69
1  27.0  3.59  122.0   0.0  40.0  40.0  30
2  26.5  2.90  121.0  16.0  20.7  29.7  72
3  29.1  3.10  114.0  44.0   2.6  26.3  68
4  43.7  2.40  105.0  32.6   5.8  10.7  42

In [75]:
df.shape

(79, 7)

### 1. Delete the column with the most missing values.

In [76]:
df.isna().sum()

0    0
1    0
2    4
3    2
4    2
5    1
6    0
dtype: int64

In [77]:
# drop column 2
df.drop(columns=2,inplace=True)

In [78]:
df.isna().sum()

0    0
1    0
3    2
4    2
5    1
6    0
dtype: int64

In [79]:
df = df.fillna(df.mean())

In [80]:
df.isna().sum()

0    0
1    0
3    0
4    0
5    0
6    0
dtype: int64

### 2. Convert the preprocessed dataset to the tensor format.

In [81]:
features = df.iloc[:,:-1]

In [82]:
features.shape

(79, 5)

In [83]:
targets = df.iloc[:,-1]
targets.shape

(79,)

In [84]:
X, y = torch.tensor(features.values), torch.tensor(targets.values)

In [85]:
X,y

(tensor([[35.3000,  2.6000, 42.4000, 24.2000, 47.1000],
         [27.0000,  3.5900,  0.0000, 40.0000, 40.0000],
         [26.5000,  2.9000, 16.0000, 20.7000, 29.7000],
         [29.1000,  3.1000, 44.0000,  2.6000, 26.3000],
         [43.7000,  2.4000, 32.6000,  5.8000, 10.7000],
         [29.5000,  2.7800, 14.0000,  0.0000, 50.0000],
         [26.3000,  2.1000, 15.7000, 15.7000, 30.4000],
         [27.6000,  3.5000, 16.8000, 23.0000, 35.2000],
         [32.6000,  2.9000, 15.8000, 15.8000, 15.0000],
         [29.5000,  2.5700, 22.0000,  2.0000, 18.0000],
         [33.4000,  2.3000,  7.5000, 14.9000,  6.0000],
         [27.6000,  2.8300, 27.9000,  6.7000, 31.7000],
         [25.5000,  3.6000,  5.3000, 21.1000, 60.0000],
         [27.7000,  3.4000, 37.4000,  9.9000, 39.9000],
         [29.4000,  2.3000, 13.5000,  6.9000, 38.3000],
         [35.1000,  3.5100, 67.2000,  2.5000,  5.9000],
         [29.9000,  2.9000,  5.3000, 55.3000, 63.2000],
         [27.9000,  3.0000,  3.5000, 23.7000, 64